const team = [
    {
        "id": 1,
        "fullname": "Kostadinov Simeon",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/simeon.jpeg?alt=media&token=4a41ccc9-d890-4541-9f2e-65432ed5b5ee",
        "country": "US",
        "city": "Miami",
        "lat": "25.761681",
        "lng": "-81.191788",
        "colorIndex": 2,
        "position": "Head of Operations & Hiring",
        "quote": "Using Speechify literally buys me my time back."
    },
    {
        "id": 2,
        "fullname": "Krishna C Aluru",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/krishna.jpg?alt=media&token=bce48df6-1b3f-48b7-8f71-d7a7f66f9022",
        "country": "US",
        "city": "Miami",
        "lat": "26.761681",
        "lng": "-80.191788",
        "colorIndex": 0,
        "position": "Head of Product & Engineering",
        "quote": "Our save to mobile feature lets me listen on the move."
    },
    {
        "id": 3,
        "fullname": "Matthiessen Alek",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/alek.jpeg?alt=media&token=96bad1f9-d9dc-4e88-a938-2792f9f88b2c",
        "country": "US",
        "city": "Miami",
        "lat": "26.761681",
        "lng": "-81.191788",
        "colorIndex": 0,
        "position": "Head of Growth",
        "quote": "Speechify = self reliance."
    },
    {
        "id": 4,
        "fullname": "Kostadinov Jan",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/jan.png?alt=media&token=1e5ce4c3-d0b7-4aca-8616-38bdd5ebd5a4",
        "country": "US",
        "city": "Miami",
        "lat": "27.761681",
        "lng": "-80.191788",
        "colorIndex": 0,
        "position": "Brand Partnerships",
        "quote": "I love the sheer convenience of being able to look away from the screen to eat while reading 😂 "
    },
    {
        "id": 5,
        "fullname": "Austin Matthiessen",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/austin.png?alt=media&token=d003d0c9-7119-42dc-8d14-1035ac6d52a6",
        "country": "US",
        "city": "New York",
        "lat": "40.712776",
        "lng": "-74.005974",
        "colorIndex": 0,
        "position": "Growth Manager",
        "quote": "Save to mobile functionality and custom voices!"
    },
    {
        "id": 6,
        "fullname": "Aaditya Sahay",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/aaditya.jpeg?alt=media&token=4bd9fccc-751d-4fa2-b011-6f8b8bc496f4",
        "country": "India",
        "city": "Gurugram",
        "lat": "28.459497",
        "lng": "77.026634",
        "colorIndex": 0,
        "position": "Web & Chrome Software Engineer",
        "quote": "Freedom. Freedom to work the way you want to, freedom to try new things, and freedom to fail."
    },
    {
        "id": 7,
        "fullname": "Anson Rosenthal",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/anson.jpeg?alt=media&token=05698785-bce6-42c8-8ece-ebc9ad460654",
        "country": "US",
        "city": "Virginia",
        "lat": "36.8516",
        "lng": "-75.9792",
        "colorIndex": 2,
        "position": "Platform Engineering Lead",
        "quote": "Highlighting makes it so much easier to follow along with what I'm listening to."
    },
    {
        "id": 8,
        "fullname": "Arun Kanojia",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/arun.jpeg?alt=media&token=a2ce0441-4460-4636-ab8e-85b8a8795a32",
        "country": "India",
        "city": "Bengaluru",
        "lat": "12.971599",
        "lng": "77.594566",
        "colorIndex": 0,
        "position": "Web & Chrome Developer",
        "quote": "It's amazing how quickly you can read anything with Speechify."
    },
    {
        "id": 9,
        "fullname": "Ben Laures",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/ben.jpeg?alt=media&token=bac26f11-4ea4-4307-91c3-d7aac4f5d7d9",
        "country": "US",
        "city": "Nomad",
        "lat": "-27.545361",
        "lng": "151.916077",
        "colorIndex": 1,
        "position": "Mobile Product Manager",
        "quote": "I start nearly everyday listening to articles about product development while making breakfast."
    },
    {
        "id": 10,
        "fullname": "Daniil Biskal",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/daniil.jpeg?alt=media&token=54d4a464-6f07-450c-8907-a467b3d0581b",
        "country": "Ukraine",
        "city": "Kharkiv",
        "lat": "49.993500",
        "lng": "36.230385",
        "colorIndex": 1,
        "position": "iOS Project Manager",
        "quote": "It's clear how much ❤️ the team has for this product."
    },
    {
        "id": 11,
        "fullname": "Dmytri Litvinenko",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/dhmitry.jpeg?alt=media&token=2b290ccb-875d-409b-ae8a-6f92db1a227f",
        "country": "Ukraine",
        "city": "Kharkiv",
        "lat": "50.993500",
        "lng": "36.230385",
        "colorIndex": 0,
        "position": "iOS Developer",
        "quote": "Speechify is all about Listening 🤓"
    },
    {
        "id": 12,
        "fullname": "Jimmy Baquiran Jr.",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/jimmy.jpeg?alt=media&token=bf327547-92aa-431a-a724-bcb7701d1ae1",
        "country": "Philippines",
        "city": "Cagayan de Oro",
        "lat": "8.454236",
        "lng": "124.631897",
        "colorIndex": 2,
        "position": "Customer Success Manager",
        "quote": "Radical autonomy! We work distributed but collectively for the same bigger goal."
    },
    {
        "id": 13,
        "fullname": "Karuna K Lingham",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/karuna.jpeg?alt=media&token=17f05d38-5955-49a0-b046-ae63846b50b0",
        "country": "India",
        "city": "Hyderabad",
        "lat": "17.385044",
        "lng": "78.486671",
        "colorIndex": 2,
        "position": "QA Engineer",
        "quote": "Great quality of voices with so many accents to choose from!"
    },
    {
        "id": 14,
        "fullname": "Lauren Tracz",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/lauren.jpeg?alt=media&token=906ee6b0-ba34-45b5-bf5d-1e96a652cfb3",
        "country": "US",
        "city": "Kansas City",
        "lat": "39.099728",
        "lng": "-94.578568",
        "colorIndex": 2,
        "position": "Copywriter",
        "quote": "This app truly changes lives. And the team here cares about making our products better for our users."
    },
    {
        "id": 15,
        "fullname": "Levan Mamulashvili",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/levan.jpeg?alt=media&token=96de4290-9e20-4dba-b755-bd8428281d35",
        "country": "Georgia",
        "city": "Tbilisi",
        "lat": "41.715137",
        "lng": "44.827095",
        "colorIndex": 1,
        "position": "iOS Engineering Lead",
        "quote": "I love the simplicity of the UI/UX and how powerful the core functionality is."
    },
    {
        "id": 16,
        "fullname": "Liam Dyer",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/liam.jpeg?alt=media&token=9bc59230-cfbd-40d0-9a67-cec8a5ef72bf",
        "country": "Canada",
        "city": "Toronto",
        "lat": "43.653225",
        "lng": "-79.383186",
        "colorIndex": 0,
        "position": "Web & Chrome Developer",
        "quote": "The text highlighting when listening is magic."
    },
    {
        "id": 17,
        "fullname": "Morhun Mykola",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/mykola.png?alt=media&token=5e75d78d-90ea-4e87-a109-d6f507e6fd68",
        "country": "Ukraine",
        "city": "Kharkiv",
        "lat": "49.993500",
        "lng": "37.230385",
        "colorIndex": 1,
        "position": "QA Engineer",
        "quote": "I love working on such an engaged team on a top of the line product that started from a gorgeous idea."
    },
    {
        "id": 18,
        "fullname": "Pankaj Agarwal",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/pankaj.jpeg?alt=media&token=da33b2ed-b38c-47af-859f-c86c3809ae59",
        "country": "India",
        "city": "Bengaluru",
        "lat": "13.971599",
        "lng": "77.594566",
        "colorIndex": 1,
        "position": "Head of Finance",
        "quote": "I love the team at Speechify. This team will break through all the barriers to deliver growth, value and audio!"
    },
    {
        "id": 19,
        "fullname": "Shaun Tennery",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/shaun.jpeg?alt=media&token=392f40f9-18e6-4fc8-9069-8cc72ea6264b",
        "country": "South Africa",
        "city": "Cape Town",
        "lat": "-33.924870",
        "lng": "18.424055",
        "colorIndex": 0,
        "position": "Web & Chrome Developer",
        "quote": "The ability to listen at 400+ WPM is a superpower."
    },
    {
        "id": 20,
        "fullname": "Sourav Chandra",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/sourav.png?alt=media&token=73224c2e-d0c2-4d16-ab93-f58552909b29",
        "country": "UAE",
        "city": "Dubai",
        "lat": "25.204849",
        "lng": "55.270782",
        "colorIndex": 2,
        "position": "Android Engineering Lead",
        "quote": "I love that Speechify gives me the ability to read any book!"
    },
    {
        "id": 21,
        "fullname": "Thomas Manuel Dias Santos",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/thomas.jpeg?alt=media&token=8353b9d0-056a-4177-b845-407babc900c2",
        "country": "France",
        "city": "Lyon",
        "lat": "45.764042",
        "lng": "4.835659",
        "colorIndex": 1,
        "position": "Web & Chrome Developer",
        "quote": "Speechify is a shortcut for learning."
    },
    {
        "id": 22,
        "fullname": "Trevor Baum",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/trevor.jpeg?alt=media&token=2f05a674-ab94-4268-bfed-5882426ed936",
        "country": "US",
        "city": "New York",
        "lat": "41.712776",
        "lng": "-74.005974",
        "colorIndex": 0,
        "position": "Design Lead",
        "quote": "I love that Speechify empowers neurodiverse people all over the world."
    },
    {
        "id": 23,
        "fullname": "Vamsee Chamakura",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/vamsee.jpeg?alt=media&token=f19b6d20-a12d-4d16-831f-a5ea53573fdb",
        "country": "India",
        "city": "Hyderabad",
        "lat": "18.385044",
        "lng": "78.486671",
        "colorIndex": 2,
        "position": "Web Product Manager",
        "quote": "Speechify helps me spend a lot less energy getting through the things I want to read."
    },
    {
        "id": 24,
        "fullname": "Vincent Anthony",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/vincent.jpeg?alt=media&token=260cb583-88ea-4749-853b-7a48c86eb79e",
        "country": "India",
        "city": "Bengaluru",
        "lat": "12.971599",
        "lng": "78.594566",
        "colorIndex": 2,
        "position": "Chrome Extension Tester",
        "quote": "Speechify is trying to fix a global clutter. It helps everyone no matter your cast, creed or color."
    },
    {
        "id": 25,
        "fullname": "Sofiia Biskal",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/sofiia.png?alt=media&token=660f609d-d164-4a58-8570-66d9001a7d98",
        "country": "Ukraine",
        "city": "Kharkiv",
        "lat": "50.993500",
        "lng": "37.230385",
        "colorIndex": 1,
        "position": "Customer Success Rep",
        "quote": "I love Speechify because it helps me improve my English and lets me communicate with people from different parts of the world."
    },
    {
        "id": 26,
        "fullname": "Tanner Walis",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/tanner.jpeg?alt=media&token=b53e9978-81a3-4dbb-a838-b7e1ee7d3208",
        "country": "US",
        "city": "Salt Lake City",
        "lat": "40.760780",
        "lng": "-111.891045",
        "colorIndex": 1,
        "position": "Web Product Manager",
        "quote": "The literally life changing impact Speechify has on some of our users is what gets me excited to work here every day."
    },
    {
        "id": 27,
        "fullname": "Tung Fam",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/tung.jpg?alt=media&token=de54fa96-6d1d-41fc-bfda-10d81db6086f",
        "country": "Ukraine",
        "city": "Kyiv",
        "lat": "50.447731",
        "lng": "30.542721",
        "colorIndex": 0,
        "position": "iOS Developer",
        "quote": "Love that fact that it helps people with learning or learning faster."
    },
    {
        "id": 28,
        "fullname": "Raquib-ul Alam",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/raquib.jpeg?alt=media&token=67b9b886-c24c-465b-9cdb-9858744796aa",
        "country": "Bangladesh",
        "city": "Dhaka",
        "lat": "23.810331",
        "lng": "90.412521",
        "colorIndex": 0,
        "position": "Android Engineer",
        "quote": "The highlighting while it reads is so good!"
    },
    {
        "id": 30,
        "fullname": "Yakeen Sewasankar (Y4D Ltd)",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/yakeen.jpg?alt=media&token=31cd705e-aa2c-4d7e-945e-1018439cd117",
        "country": "UK",
        "city": "London",
        "lat": "52.507351",
        "lng": "-0.127758",
        "colorIndex": 0,
        "position": "Platform Engineer",
        "quote": "I love working a Speechify. It gives me the opportunity to grow, collaborate and solve hard problems — all while being fully remote!"
    },
    {
        "id": 31,
        "fullname": "Rita Chandra",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/rita.jpeg?alt=media&token=21545e5b-2490-4542-bb0d-26bbf926d23e",
        "country": "UAE",
        "city": "Dubai",
        "lat": "25.204849",
        "lng": "56.270782",
        "colorIndex": 0,
        "position": "Customer Success Rep",
        "quote": "I like that I can work from anywhere without being limited by a geographical location!"
    },
    {
        "id": 32,
        "fullname": "Dan Darrah",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/dan.jpeg?alt=media&token=d007ea2d-b403-4bb2-b7e4-c9a9d63a9f8e",
        "country": "Canada",
        "city": "Toronto",
        "lat": "44.653225",
        "lng": "-79.383186",
        "colorIndex": 2,
        "position": "Copywriter",
        "quote": "At Speechify, I work with a brilliant, global team to create tools that empower and inspire. What’s not to love?"
    },
    {
        "id": 33,
        "fullname": "Anthony Fanelli (Aphotic Productions LLC)",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/anthony.png?alt=media&token=166c24e3-3a44-4268-9cc8-17811f823e90",
        "country": "US",
        "city": "Los Angeles",
        "lat": "34.052235",
        "lng": "-118.243683",
        "colorIndex": 2,
        "position": "Creative Content Producer",
        "quote": "I love that Speechify gives me the creative freedom and trust to do great work."
    },
    {
        "id": 34,
        "fullname": "Rebecca Zak (Becky)",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/becky.jpg?alt=media&token=d6b2db00-0056-44f2-9125-a940d096e3a7",
        "country": "US",
        "city": "Playa Del Carmen",
        "lat": "32.828159",
        "lng": "-115.558990",
        "colorIndex": 2,
        "position": "Video Producer/Ad Specialist",
        "quote": "I love that we're helping people learn more effectively and we're innovative."
    },
    {
        "id": 35,
        "fullname": "Aditi Jhalani",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/aditi.jpg?alt=media&token=e1c563df-1501-4178-95ae-cf8fa9ab346f",
        "country": "India",
        "city": "Delhi",
        "lat": "28.704060",
        "lng": "77.102493",
        "colorIndex": 1,
        "position": "Recruiting Coordinator",
        "quote": "I get to work with a team of happy people and can work from anywhere in the world."
    },
    {
        "id": 36,
        "fullname": "Vidyasagar Menon",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/vidya.jpg?alt=media&token=672a6d70-498d-42af-ab23-d8bf6112d249",
        "country": "UAE",
        "city": "Dubai",
        "lat": "26.204849",
        "lng": "56.270782",
        "colorIndex": 0,
        "position": "Recruiting Coordinator",
        "quote": "Speechify gives people reading superpowers!"
    },
    {
        "id": 37,
        "fullname": "Arjen Kerr Teves",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/arjen.jpeg?alt=media&token=c56d0f23-80ea-477b-b765-f87e6210c4b9",
        "country": "Philippines",
        "city": "Nomad",
        "lat": "-28.545361",
        "lng": "151.916077",
        "colorIndex": 1,
        "position": "Creative Content Producer",
        "quote": "The best part about Speechify is the people!"
    },
    {
        "id": 38,
        "fullname": "Gabriel Romualdo",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/gabriel.png?alt=media&token=19e685cf-db6c-483b-b4a9-b593469cb71a",
        "country": "US",
        "city": "Boston",
        "lat": "42.360081",
        "lng": "-71.058884",
        "colorIndex": 0,
        "position": "API & B2B Engineering Lead",
        "quote": "I love our celebrity voices and how many different options there are."
    },
    {
        "id": 39,
        "fullname": "Sahlie Baquiran",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/sahlie.jpg?alt=media&token=4b0c2429-33d7-4cce-b780-c9fc95b00ad5",
        "country": "Philippines",
        "city": "Cagayan de Oro",
        "lat": "8.454236",
        "lng": "125.631897",
        "colorIndex": 2,
        "position": "Recruiting Coordinator",
        "quote": "Aside from flexibility and learning new skills, I get to work with great people who have endless goals in changing the future of reading."
    },
    {
        "id": 41,
        "fullname": "Chintip Winn",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/chin.jpeg?alt=media&token=52c89aa5-488f-489e-b84f-5c200f0e55c9",
        "country": "US",
        "city": "Chicago",
        "lat": "41.878113",
        "lng": "-87.629799",
        "colorIndex": 0,
        "position": "Platform Engineer",
        "quote": "Working with my team is the best part about Speechify 😎"
    },
    {
        "id": 42,
        "fullname": "Christine (Hui Ye)",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/christine.jpeg?alt=media&token=c58fab3f-c70e-4558-9f28-8ea5970080c4",
        "country": "US",
        "city": "Los Angeles",
        "lat": "35.052235",
        "lng": "-118.243683",
        "colorIndex": 2,
        "position": "Product Designer",
        "quote": "I like listening to books rather than reading them. I think Speechify really solves a lot of pain points for a lot of people."
    },
    {
        "id": 43,
        "fullname": "Sadman Sarar",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/sadman.jpeg?alt=media&token=e134cdc8-2dbc-4b72-a63b-e5ba3ab86f3f",
        "country": "Bangladesh",
        "city": "Dhaka",
        "lat": "24.810331",
        "lng": "91.412521",
        "colorIndex": 2,
        "position": "Android Engineer",
        "quote": "Love how Speechify gives me the freedom to take initiative to improve the product, which also gives me an immense opportunity to grow."
    },
    {
        "id": 44,
        "fullname": "Adam Sliwakowski (Codetown)",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/adam.jpeg?alt=media&token=45790233-3bb7-483d-bba3-5f1538f249f4",
        "country": "Poland",
        "city": "Katowice",
        "lat": "50.264893",
        "lng": "19.023781",
        "colorIndex": 2,
        "position": "iOS Developer",
        "quote": "I love watching the hypergrowth of Speechify from the front seat."
    },
    {
        "id": 45,
        "fullname": "Roman Taraban (Codescale GmbH)",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/roman.jpeg?alt=media&token=5a3f2057-fa29-48fa-9b96-3bce7171882d",
        "country": "Germany",
        "city": "Berlin",
        "lat": "52.520008",
        "lng": "13.404954",
        "colorIndex": 1,
        "position": "Platform Engineer",
        "quote": "Listening + Reading = Better comprehension."
    },
    {
        "id": 46,
        "fullname": "Mattia Basile",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/mattia.jpeg?alt=media&token=e80468b5-7a9f-4413-b239-a9f637aca814",
        "country": "Netherlands",
        "city": "Breda",
        "lat": "51.571915",
        "lng": "4.768323",
        "colorIndex": 0,
        "position": "Account Executive",
        "quote": "I can listen to things I wouldn’t read otherwise."
    },
    {
        "id": 47,
        "fullname": "Michael Han",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/han.jpeg?alt=media&token=2356fca2-8aa2-4bd0-8c65-30055169a7dc",
        "country": "Czech Republic",
        "city": "Prague",
        "lat": "50.075539",
        "lng": "14.437800",
        "colorIndex": 2,
        "position": "Web & Chrome Engineer",
        "quote": "I love the flexibility, variety of work, good friendships, and technical proficiency I get to use every day."
    },
    {
        "id": 48,
        "fullname": "Arnab Mukherjee (2467252 Ontario Inc)",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/arnab.jpg?alt=media&token=f93d53ca-3bf6-443e-a635-d5b9eeaf5834",
        "country": "US",
        "city": "Seattle",
        "lat": "47.606209",
        "lng": "-122.332069",
        "colorIndex": 0,
        "position": "Mobile Product Manager & Strategy",
        "quote": "This is the best place to make a global impact while treating others with kindness and love."
    },
    {
        "id": 49,
        "fullname": "Dhriti Kalpa Saha",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/dhriti.jpg?alt=media&token=f6020c9d-7b24-4bec-b80f-ac021ece1f40",
        "country": "India",
        "city": "Agartala",
        "lat": "23.831457",
        "lng": "91.286781",
        "colorIndex": 2,
        "position": "Web & Chrome Engineer",
        "quote": "I get to set my own goals and crush them with support from some of the most talented people in the industry. Speechify is the perfect example of outstanding product meets awesome culture."
    },
    {
        "id": 50,
        "fullname": "Kenny Batista",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/kenny.png?alt=media&token=786b8150-74f0-4bba-b2d9-dedd7246cbad",
        "country": "US",
        "city": "Miami",
        "lat": "27.761681",
        "lng": "-81.191788",
        "colorIndex": 1,
        "position": "Product Manager, B2B",
        "quote": "The people are the best part about working here!"
    },
    {
        "id": 51,
        "fullname": "Pedro Mendes Félix da Costa",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/pedro.jpg?alt=media&token=a496dbeb-f4c2-475f-a665-134203afd19c",
        "country": "Portugal",
        "city": "Braga",
        "lat": "41.545448",
        "lng": "-8.426507",
        "colorIndex": 2,
        "position": "Platform Engineer",
        "quote": "I love the people I work with and the company's culture."
    },
    {
        "id": 52,
        "fullname": "Tedo Chubinidze",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/tedo.jpg?alt=media&token=591373b3-b45d-463a-84df-936bdeafb876",
        "country": "Georgia",
        "city": "Tbilisi",
        "lat": "42.715137",
        "lng": "44.827095",
        "colorIndex": 0,
        "position": "iOS Developer",
        "quote": "I love that it helps a lot of people throughout the world and the friendly environment that welcomed me. Plus, the more I work with code the more stunned I am by the awesome work of my coworkers!"
    },
    {
        "id": 53,
        "fullname": "Hemant Kejriwal",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/hemant.jpg?alt=media&token=9b3a1d7f-f62a-4d17-8384-63ddefed462a",
        "country": "India",
        "city": "Bengaluru",
        "lat": "11.971599",
        "lng": "77.594566",
        "colorIndex": 2,
        "position": "Finance Consultant",
        "quote": "The people here make it awesome."
    },
    {
        "id": 54,
        "fullname": "William Gordon Peter Fowler",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/william.jpeg?alt=media&token=e2142c0e-6fef-4a6d-b2f2-2c19128268dc",
        "country": "US",
        "city": "Los Angeles",
        "lat": "34.052235",
        "lng": "-119.243683",
        "colorIndex": 1,
        "position": "Consultant",
        "quote": "Speechify makes reading and learning surprisingly easy. It has the potential to change the way that people view themselves and their abilities. "
    },
    {
        "id": 55,
        "fullname": "Kai Robin Krause",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/kai.jpeg?alt=media&token=efb2ab61-6699-4355-a4dd-d904ae4cda93",
        "country": "Switzerland",
        "city": "Solothurn",
        "lat": "47.208835",
        "lng": "7.532291",
        "colorIndex": 2,
        "position": "Platform Engineer",
        "quote": "I love that Speechify allows me to consume texts as fast as audible books 🥳"
    },
    {
        "id": 56,
        "fullname": "Tigran Grigorian",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/tigran.jpg?alt=media&token=baf2b74b-505d-4f7c-b9d2-7bfad15c29f3",
        "country": "Armenia",
        "city": "Yerevan",
        "lat": "40.179188",
        "lng": "44.499104",
        "colorIndex": 2,
        "position": "Web & Chrome Engineer",
        "quote": "Speechify increases the flexibility of getting information and learning."
    },
    {
        "id": 57,
        "fullname": "Reinhard Hafenscher",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/reinhard.jpg?alt=media&token=e2d8770f-b4e2-4c37-97c1-694cd96d75e5",
        "country": "Austria",
        "city": "Vienna",
        "lat": "48.208176",
        "lng": "16.373819",
        "colorIndex": 1,
        "position": "Platform Engineer",
        "quote": "I like the freedom you have in where you work, when you work, and how you work here."
    },
    {
        "id": 58,
        "fullname": "Jose Miguel F. Palmares III",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/jose.jpeg?alt=media&token=166e907f-7246-479a-adf5-7f487af387b6",
        "country": "Philippines",
        "city": "Dapitan City",
        "lat": "8.625319",
        "lng": "123.394571",
        "colorIndex": 0,
        "position": "Customer Success Rep",
        "quote": "Work environment is what I love about working at Speechify. Love the people, love the pay, love everything about it."
    },
    {
        "id": 59,
        "fullname": "Ian Fritch Escobarte Reyes",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/ian.jpg?alt=media&token=7b0830fa-9cd7-4827-9772-12f51d094284",
        "country": "Philippines",
        "city": "Lapu-Lapu City",
        "lat": "10.266182",
        "lng": "123.997292",
        "colorIndex": 0,
        "position": "Customer Success Rep",
        "quote": "Work-life balance is great!!!"
    },
    {
        "id": 60,
        "fullname": "Lovella Tubera Balverde",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/lovella.jpg?alt=media&token=add652b7-73a9-46a9-989a-16f165ddde85",
        "country": "Philippines",
        "city": "Cagayan de Oro City",
        "lat": "9.454236",
        "lng": "124.631897",
        "colorIndex": 2,
        "position": "Customer Success Rep",
        "quote": "Great culture and management."
    },
    {
        "id": 61,
        "fullname": "Jeddah Lynn Bautista-Medallo",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/jeddah.jpeg?alt=media&token=17e7e7a5-274c-450e-9499-673336b4e944",
        "country": "Philippines",
        "city": "Iligan City",
        "lat": "8.2280",
        "lng": "124.2452",
        "colorIndex": 0,
        "position": "Customer Success Rep",
        "quote": "I’m working with a great team, helping awesome customers, and supporting an impactful product."
    },
    {
        "id": 62,
        "fullname": "Romielyn Macapayad Baladjay",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/romielyn.jpg?alt=media&token=e5fd6779-bef8-44da-91f8-d44cdf88c1d7",
        "country": "Philippines",
        "city": "Malanang Opol Misamis Oriental",
        "lat": "8.4895",
        "lng": "124.5667",
        "colorIndex": 1,
        "position": "Customer Success Rep",
        "quote": "With Speechify, I got good compensation with awesome leaders and approachable engineers to help me provide great customer service to our users."
    },
    {
        "id": 63,
        "fullname": "Kristy Lovell Amores",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/kristy.jpg?alt=media&token=1242acac-e7fc-4176-8234-fb8d427da94b",
        "country": "Philippines",
        "city": "Cagayan de Oro",
        "lat": "9.454236",
        "lng": "125.631897",
        "colorIndex": 2,
        "position": "Customer Success Rep",
        "quote": "The play button and its accuracy is amazing! 🙂"
    },
    {
        "id": 64,
        "fullname": "Sheila Marie Tan",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/sheila.jpeg?alt=media&token=e6d768cb-0aec-4073-920f-0a9a606e7f17",
        "country": "Philippines",
        "city": "Iligan City",
        "lat": "9.2280",
        "lng": "124.2452",
        "colorIndex": 1,
        "position": "Customer Success Rep",
        "quote": "Awesome people, great product, and flexibility at work. I am blessed to be part of the Speechify team."
    },
    {
        "id": 65,
        "fullname": "Jerylle Peralta",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/jerylle.jpeg?alt=media&token=1d183228-17ed-4fc1-8d0b-1aca0a939750",
        "country": "Philippines",
        "city": "Cebu City",
        "lat": "10.31672",
        "lng": "123.89071",
        "colorIndex": 0,
        "position": "Customer Success Rep",
        "quote": "Great place to work. Speechify is one of the best companies I have worked so far. Awesome company culture where everyone lends a helping hand!"
    },
    {
        "id": 66,
        "fullname": "Andy Andersen",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/andy.jpeg?alt=media&token=b6be19c1-e0f0-4451-b704-418b1631ee7d",
        "country": "US",
        "city": "Nomad",
        "lat": "-27.545361",
        "lng": "152.916077",
        "colorIndex": 1,
        "position": "Principal Product Manager",
        "quote": "Great momentum and great people!"
    },
    {
        "id": 67,
        "fullname": "Jordan Gannon",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/joe.jpeg?alt=media&token=c512c0ed-bcba-41a3-a2e1-cbe5ffb033cd",
        "country": "UK",
        "city": "Cambridge",
        "lat": "52.205338",
        "lng": "0.121817",
        "colorIndex": 1,
        "position": "Organic Social Media Lead",
        "quote": "Speechify is great because it brings talent all over the world to work together."
    },
    {
        "id": 68,
        "fullname": "Valentin Kostadinov",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/valentin.jpeg?alt=media&token=b2b5d6b9-c2f9-4d08-8cde-6d3348f2b06e",
        "country": "US",
        "city": "Nomad",
        "lat": "-27.545361",
        "lng": "150.916077",
        "colorIndex": 0,
        "position": "Web & Chrome Engineer",
        "quote": "It's a unique product market fit."
    },
    {
        "id": 69,
        "fullname": "Myron Satsyk Sergeevich",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/myron.jpg?alt=media&token=f5c6f459-6ee4-4931-a42c-8715f9d07929",
        "country": "Ukraine",
        "city": "Svaliava",
        "lat": "48.545570",
        "lng": "22.989480",
        "colorIndex": 1,
        "position": "QA Engineer",
        "quote": "Amazing product that helps people all around the world improve their lives!"
    },
    {
        "id": 70,
        "fullname": "Shepetukha Anton Sergeevich",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/anton.jpeg?alt=media&token=39d6db77-b840-47ea-8822-5d07d2e2e554",
        "country": "Ukraine",
        "city": "Kyiv",
        "lat": "51.447731",
        "lng": "30.542721",
        "colorIndex": 1,
        "position": "iOS Developer",
        "quote": "The best part about Speechify is the team ❤️"
    },
    {
        "id": 71,
        "fullname": "Avtandil Morchadze",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/avtandil.jpeg?alt=media&token=e9964040-50ba-40b3-b89f-02de66ca376a",
        "country": "Georgia",
        "city": "Tbilisi",
        "lat": "41.715137",
        "lng": "45.827095",
        "colorIndex": 0,
        "position": "QA Engineer",
        "quote": "Speechify helps people change their daily lives. I love the flexibility, friendly environment, and that the company's \"why\" is behind everything we do."
    },
    {
        "id": 72,
        "fullname": "Georgina Natalie Cuartero Paulino",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/kim.png?alt=media&token=c13bba65-3ca3-4e06-b040-6dc40b6bf8c3",
        "country": "Philippines",
        "city": "San Leonardo, Nueva Ecija",
        "lat": "15.3729",
        "lng": "120.9532",
        "colorIndex": 0,
        "position": "Customer Success Rep",
        "quote": "I love how I'm able to work with great people at the comfort of my home."
    },
    {
        "id": 73,
        "fullname": "Jorgen Arevalo",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/jorgen.jpeg?alt=media&token=36810149-9948-4501-9ce3-3354b6609ecd",
        "country": "Philippines",
        "city": "Cabanatuan City, Nueva Ecija",
        "lat": "16.3729",
        "lng": "120.9532",
        "colorIndex": 1,
        "position": "Customer Success Rep",
        "quote": "I love that Speechify supports diversity so we can work with people around the globe."
    },
    {
        "id": 74,
        "fullname": "Edgar Joseph Tan",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/edgar.png?alt=media&token=5eb8739d-af78-4ed7-bd79-7a51d411df0d",
        "country": "Philippines",
        "city": "Iligan City",
        "lat": "8.2280",
        "lng": "125.2452",
        "colorIndex": 0,
        "position": "Customer Success Rep",
        "quote": "A family-oriented team that should be called \"The Amazing Speechify\"."
    },
    {
        "id": 75,
        "fullname": "Shaurabh Kumar SIngh",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/shaurabh.png?alt=media&token=136dbde1-4398-4dee-ada9-5a9590e104d7",
        "country": "India",
        "city": "Bengaluru",
        "lat": "8.2280",
        "lng": "123.2452",
        "colorIndex": 1,
        "position": "QA Engineer",
        "quote": "People rarely succeed unless they have fun in what they are doing. We at Speechify own every bit of what we do, it belongs to us, here work is more like having fun."
    },
    {
        "id": 76,
        "fullname": "Dmytro Ripa",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/dmytro.jpeg?alt=media&token=01961a26-9687-4456-9099-2f1f03e39e15",
        "country": "Ukraine",
        "city": "Kyiv",
        "lat": "50.447731",
        "lng": "31.542721",
        "colorIndex": 2,
        "position": "iOS Developer",
        "quote": "Great app and idea that helps millions of people!"
    },
    {
        "id": 77,
        "fullname": "Imrane Talibi",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/imrane.jpg?alt=media&token=ae27e773-3433-43b9-9ffb-d9fd67ad1e06",
        "country": "Morocco",
        "city": "Temara",
        "lat": "33.9203",
        "lng": "6.9274",
        "colorIndex": 0,
        "position": "Android Engineer",
        "quote": "I can listen to books everywhere!"
    },
    {
        "id": 78,
        "fullname": "Becket Media Inc (Jack Oremus)",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/jack.jpg?alt=media&token=189f99be-82f0-47b7-915c-4d5b9ff8dfe6",
        "country": "US",
        "city": "Miami",
        "lat": "25.761681",
        "lng": "-82.191788",
        "colorIndex": 1,
        "position": "Video/Media Production",
        "quote": "What I like most about working with Speechify is being surrounded by motivated, intelligent individuals who constantly push me to become better in every aspect of my life."
    },
    {
        "id": 79,
        "fullname": "Kaitlin Danille Dalton",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/kaitlin.jpg?alt=media&token=6d9970e8-23b8-48df-a774-e36261911fc2",
        "country": "US",
        "city": "Seattle",
        "lat": "48.606209",
        "lng": "-122.332069",
        "colorIndex": 2,
        "position": "Recruiting Manager",
        "quote": "The best parts are the impact Speechify has on customers lives and the increase of my reading/listening speed!"
    },
    {
        "id": 80,
        "fullname": "Enes Grahovac",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/enes.jpg?alt=media&token=bf1440c8-6400-4acf-a88c-14c6b0be8665",
        "country": "US",
        "city": "Miami",
        "lat": "26.761681",
        "lng": "-82.191788",
        "colorIndex": 1,
        "position": "Engineer",
        "quote": "I love the fully remote, high achieving culture. And that I can be in a 5 person meeting where people are in 4 different countries."
    },
    {
        "id": 83,
        "fullname": "Akshita Singh",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/akshita.jpeg?alt=media&token=65f41951-90da-4be3-b4f6-83a1dcd81d12",
        "country": "India",
        "city": "Delhi",
        "lat": "29.704060",
        "lng": "77.102493",
        "colorIndex": 0,
        "position": "Recruiting Coordinator",
        "quote": "The best part about working with Speechify is that even though the company is remote, there has never been a communication gap. It gives you the opportunity to grow and learn with people from diverse cultures across the globe."
    },
    {
        "id": 84,
        "fullname": "Vinti Agarwal",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/vinti.jpeg?alt=media&token=fa183af6-0479-4a34-9ce7-acbaadfdd234",
        "country": "India",
        "city": "Gurugram",
        "lat": "29.459497",
        "lng": "77.026634",
        "colorIndex": 2,
        "position": "People Operations",
        "quote": "I love the freedom and complete ownership to give your best, while working with one of the smartest groups of people who are equally as humble."
    },
    {
        "id": 85,
        "fullname": "Giorgi Lashvili",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/giorgi.jpg?alt=media&token=6affb06c-a8da-4b37-9369-bac693a405f5",
        "country": "Georgia",
        "city": "Tbilisi",
        "lat": "42.715137",
        "lng": "43.827095",
        "colorIndex": 1,
        "position": "iOS Developer",
        "quote": "First of all, I love the people who work at Speechify. Plus the product is amazing, has really good features, and it makes it easy to read. "
    },
    {
        "id": 86,
        "fullname": "Dmytro Malyshev",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/dmytro.jpg?alt=media&token=5928a0de-f021-4cda-aed1-358ccc7f20c0",
        "country": "Ukraine",
        "city": "Kyiv",
        "lat": "51.447731",
        "lng": "31.542721",
        "colorIndex": 0,
        "position": "Senior Product Designer",
        "quote": "Knowing how many important things our users have achieved by using their time more effectively thanks to Speechify inspires me."
    },
    {
        "id": 88,
        "fullname": "Rajiv Tikoo",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/rajiv.png?alt=media&token=4baa4f3a-0e65-45ae-99cf-b03c81aa3b6f",
        "country": "US",
        "city": "Seattle",
        "lat": "47.606209",
        "lng": "-123.332069",
        "colorIndex": 1,
        "position": "Head of Engineering",
        "quote": "The best parts are the people, the mission, and the energy."
    },
    {
        "id": 89,
        "fullname": "Carlos Andres Lastres Sancho (Art Dynasty Ltd)",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/carlos.jpeg?alt=media&token=3d04eb9b-bddf-4f2e-a468-05d7baa34745",
        "country": "China",
        "city": "Shenzhen",
        "lat": "22.543097",
        "lng": "114.057861",
        "colorIndex": 2,
        "position": "Senior Product Designer",
        "quote": "As a designer, Speechify gives me a digital environment and the stimulus to keep me motivated, inspired, driven, and creative."
    },
    {
        "id": 90,
        "fullname": "Nevres Tuba Erayman",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/tuba.jpg?alt=media&token=47a24572-9d4f-42c1-8e42-43d93a879d77",
        "country": "Turkey",
        "city": "Istanbul",
        "lat": "41.008240",
        "lng": "28.978359",
        "colorIndex": 2,
        "position": "Recruiter",
        "quote": "I love being part of a company that built a product I love and use everyday, and that I get to work with the most amazing people who are smart and full of kindness."
    },
    {
        "id": 91,
        "fullname": "Oluwasayo Agboola Oladeji",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/sayo.jpg?alt=media&token=9386f180-d0c4-40be-bdbd-7d6fa688e87e",
        "country": "Finland",
        "city": "Helsinki",
        "lat": "60.169857",
        "lng": "24.938379",
        "colorIndex": 1,
        "position": "Platform Engineer",
        "quote": "Our API integration is so sleek!"
    },
    {
        "id": 92,
        "fullname": "Michael Angelo Balvarde",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/michael.png?alt=media&token=91da6010-bfd8-4f8f-8fa6-03cf07357831",
        "country": "Philippines",
        "city": "Cagayan de Oro City",
        "lat": "7.454236",
        "lng": "124.631897",
        "colorIndex": 1,
        "position": "Customer Success Rep",
        "quote": "Speechify is family. This is the BEST type of company culture!"
    },
    {
        "id": 93,
        "fullname": "Maria Ines S Reyes",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/maria.jpeg?alt=media&token=30d841e4-85aa-4a8f-a490-fbda10c06bc6",
        "country": "Philippines",
        "city": "Lapu-Lapu City",
        "lat": "11.266182",
        "lng": "123.997292",
        "colorIndex": 1,
        "position": "Customer Service Rep",
        "quote": "I love the virtual setup and being able to collaborate with people across the globe!"
    },
    {
        "id": 94,
        "fullname": "Oindri Mukherjee",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/tia.jpeg?alt=media&token=980fb0f9-921c-4801-aa38-5983e06c7c14",
        "country": "Canada",
        "city": "Toronto",
        "lat": "43.653225",
        "lng": "-80.383186",
        "colorIndex": 2,
        "position": "Sourcer",
        "quote": "We are the product and the team. The product wouldn't be what it is without our amazing team. And we wouldn't be a team without our shared love for Speechify! A win-win."
    },
    {
        "id": 95,
        "fullname": "Aaron Kelvin Onu",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/aaron.jpg?alt=media&token=66e2c01e-4cc7-47a1-88f1-cb0fd8af42e0",
        "country": "Nigeria",
        "city": "Lagos",
        "lat": "6.524379",
        "lng": "3.379206",
        "colorIndex": 1,
        "position": "Senior Product Designer",
        "quote": "The thing I like most about working at Speechify is the lovely, amazing, and very intelligent people I get to work with. It's really lovely working with different people who are all so welcoming and well intentioned. Love it!"
    },
    {
        "id": 96,
        "fullname": "Noel Oclarit",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/noel.jpg?alt=media&token=4d32e1f4-0e7f-4c40-b617-5240f42af346",
        "country": "Philippines",
        "city": "Cagayan de Oro",
        "lat": "8.454236",
        "lng": "123.631897",
        "colorIndex": 2,
        "position": "Workforce Management",
        "quote": "I love working with talented and kind individuals who share the mission to make reading an awesome experience for everyone."
    },
    {
        "id": 97,
        "fullname": "Raheel Kazi",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/raheel.jpeg?alt=media&token=9f845d56-d092-40d1-861c-dc1a7c34d86a",
        "country": "US",
        "city": "Seattle",
        "lat": "46.606209",
        "lng": "-122.332069",
        "colorIndex": 2,
        "position": "Web Engineering Lead",
        "quote": "The mission, the people, the passion and the product make working here great."
    },
    {
        "id": 99,
        "fullname": "Brian Casey",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/brian.jpg?alt=media&token=f0c827cc-0589-43d9-978b-5e21b67c3d6a",
        "country": "US",
        "city": "Seattle",
        "lat": "47.606209",
        "lng": "-121.332069",
        "colorIndex": 2,
        "position": "Senior Recruiter",
        "quote": "What I like most is working for a product that helps people and removes some of the barriers for anyone who struggles to read. I also love the people here and how kind they are."
    },
    {
        "id": 100,
        "fullname": "Hojung Kim",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/hojung.jpg?alt=media&token=c6f9046e-2b0b-4727-99e2-c194ad215810",
        "country": "US",
        "city": "Austin",
        "lat": "30.267153",
        "lng": "-97.743057",
        "colorIndex": 1,
        "position": "Product Manager",
        "quote": "I love that Speechify helps me spend a lot less energy getting through the things I read."
    },
    {
        "id": 101,
        "fullname": "Conrad Joseph Abraham",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/conrad.jpeg?alt=media&token=95dd6899-ed89-4484-9b60-6d25b796f9a1",
        "country": "US",
        "city": "Atlanta",
        "lat": "33.748783",
        "lng": "-84.388168",
        "colorIndex": 0,
        "position": "SEO Lead",
        "quote": "Learning to love the product. It is pretty convenient and efficient. I can listen faster than I can read. Company-wise, love the energy, the big scary vision and goals. I love the challenge."
    },
    {
        "id": 102,
        "fullname": "Jeffrey Fu-sing Lee",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/jeff.jpeg?alt=media&token=7db36f75-cfeb-43a5-8117-ded4fa388f94",
        "country": "US",
        "city": "Minneapolis",
        "lat": "44.9778",
        "lng": "-93.2650",
        "colorIndex": 2,
        "position": "Customer Lifecycle",
        "quote": "Love the company mission."
    },
    {
        "id": 103,
        "fullname": "Grant Vollmer",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/grant.png?alt=media&token=f02775b7-e71b-41da-9876-c2c9ca0b26b3",
        "country": "US",
        "city": "Miami",
        "lat": "27.761681",
        "lng": "-82.191788",
        "colorIndex": 0,
        "position": "Head of Brand",
        "quote": "The Speechify family is an incredibly-bright team. We're a unique group of experts passionate about helping people unlock information and are giving a new voice to the internet. We’re just getting started."
    },
    {
        "id": 104,
        "fullname": "Tyler Weitzman",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/tyler.png?alt=media&token=b580a711-d9cb-48c3-859d-304e1a9bb722",
        "country": "US",
        "city": "Miami",
        "lat": "24.761681",
        "lng": "-80.191788",
        "colorIndex": 2,
        "position": "Head of AI",
        "quote": "Leadership at Speechify is driven by love, and everyone is always working together to help drive our mission to be the voice of the internet"
    },
    {
        "id": 106,
        "fullname": "Chloe Zak",
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/speechify-slack-bot.appspot.com/o/chloe.jpg?alt=media&token=1f637888-6a38-4771-8d57-e0d247c74198",
        "country": "US",
        "city": "Los Angeles",
        "lat": "33.0522",
        "lng": "-117.2437",
        "colorIndex": 2,
        "position": "Video Producer/Ad Specialist",
        "quote": "I love the passion that everyone who works at Speechify has. And I love how Speechify is changing and improving how people access their information."
    }
]
